import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <header className="flex justify-between items-center p-8">
          <h1 className="text-6xl">🏫</h1>

          <nav>
            <ul>
              <li>Students</li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
